# ~/.config/helix/themes/solarized-custom.toml

"ui.background" = { bg = "base03" }
"ui.text" = "base1"
"ui.text.focus" = { fg = "base1", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"ui.cursor.primary" = { fg = "base03", bg = "cyan" }
"ui.cursor.match" = { bg = "base01" }
"ui.linenr" = "base01"
"ui.linenr.selected" = { fg = "cyan", modifiers = ["bold"] }
"ui.statusline" = { fg = "base1", bg = "base02" }
"ui.statusline.inactive" = { fg = "base01", bg = "base03" }
"ui.popup" = { bg = "base02" }
"ui.window" = "base01"
"ui.help" = { bg = "base02" }

"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"diagnostic.warning" = { underline = { style = "curl", color = "yellow" } }
"diagnostic.info" = { underline = { style = "curl", color = "blue" } }
"diagnostic.hint" = { underline = { style = "curl", color = "cyan" } }

"error" = "red"
"warning" = "yellow"
"info" = "blue"
"hint" = "cyan"

"comment" = "base01"
"constant" = "cyan"
"constant.numeric" = "cyan"
"string" = "cyan"
"function" = "blue"
"keyword" = "green"
"operator" = "green"
"type" = "yellow"
"variable" = "base1"
"variable.parameter" = "base1"

[palette]
base03   = "#0f0f0f"  
base02   = "#073642"
base01   = "#586e75"
base00   = "#657b83"
base0    = "#839496"
base1    = "#93a1a1"
base2    = "#eee8d5"
base3    = "#fdf6e3"

yellow  = "#b58900"
orange  = "#cb4b16"
red     = "#dc322f"
magenta = "#d33682"
violet  = "#6c71c4"
blue    = "#268bd2"
cyan    = "#2aa198"  
green   = "#859900"
