# ~/.config/alacritty/alacritty.toml

[general]
import = []
live_config_reload = true

# [terminal]
# shell = { program = "zellij" }

[window]
opacity = 1
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "full"

[font]
size = 12.0

[font.normal]
family = "VictorMono Nerd Font"
style = "SemiBold"

[font.bold]
family = "VictorMono Nerd Font"
style = "Bold"

[font.italic]
family = "VictorMono Nerd Font"
style = "SemiBold Italic"

# Solarized Dark com fundo preto profundo
[colors.primary]
background = "#0f0f0f"  # preto profundo
foreground = "#93a1a1"  # base1 Solarized

[colors.normal]
black   = "#073642"   # base02
red     = "#dc322f"   # red
green   = "#859900"   # green
yellow  = "#b58900"   # yellow
blue    = "#268bd2"   # blue
magenta = "#d33682"   # magenta
cyan    = "#2aa198"   # cyan 
white   = "#93a1a1"   # base1

[colors.bright]
black   = "#002b36"   # base03
red     = "#cb4b16"   # orange
green   = "#586e75"   # base01
yellow  = "#657b83"   # base00
blue    = "#839496"   # base0
magenta = "#6c71c4"   # violet
cyan    = "#93a1a1"   # base1
white   = "#fdf6e3"   # base3

[colors.selection]
text = "#0f0f0f"
background = "#2aa198"
